name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ["typescript"] # Changed from "javascript"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  bundle-analysis:
    name: Bundle Size Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Analyse bundle size
        run: |
          echo "## Bundle Size Analysis" >> bundle-analysis.md
          echo "" >> bundle-analysis.md
          echo "### Build Output" >> bundle-analysis.md
          ls -la dist/ >> bundle-analysis.md || echo "No dist directory found" >> bundle-analysis.md
          echo "" >> bundle-analysis.md
          echo "### File Sizes" >> bundle-analysis.md
          du -h dist/* >> bundle-analysis.md 2>/dev/null || echo "No files to analyze" >> bundle-analysis.md
          echo "" >> bundle-analysis.md
          echo "### Total Package Size" >> bundle-analysis.md
          du -sh dist/ >> bundle-analysis.md 2>/dev/null || echo "No dist directory" >> bundle-analysis.md

      - name: Upload bundle analysis
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis
          path: bundle-analysis.md
          retention-days: 30
