name: Dependency Updates

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Update dependencies
        run: |
          pnpm update --latest
          pnpm install

      - name: Check if there are changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Run tests after update
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          pnpm build
          pnpm lint
          pnpm test
        env:
          SKIP_INTEGRATION_TESTS: true

      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update dependencies'
          title: 'chore(deps): weekly dependency updates'
          body: |
            ## Automated Dependency Updates
            
            This PR updates all dependencies to their latest versions.
            
            ### What's Changed
            - Updated all dependencies to latest versions
            - Verified that all tests pass
            - Confirmed build still works
            
            ### Testing
            - ✅ Build passes
            - ✅ Linting passes  
            - ✅ Tests pass
            
            This is an automated PR created by the dependency update workflow.
          branch: chore/dependency-updates
          delete-branch: true
          labels: |
            dependencies
            automated
            chore
