name: Publish to npm

on:
  push:
    tags:
      - "v*"
  release:
    types: [published]

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for npm provenance
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"
          registry-url: "https://registry.npmjs.org"

      - name: Enable Corepack and install latest pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run CI pipeline
        run: pnpm run ci
        env:
          SKIP_INTEGRATION_TESTS: true

      - name: Build package
        run: pnpm build

      - name: Verify package can be published
        run: pnpm pack --dry-run

      - name: Publish to npm
        run: pnpm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            🚀 **Typicord ${{ github.ref_name }}**

            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.

            ## Installation
            ```bash
            npm install typicord@${{ github.ref_name }}
            ```

            ## What's Changed
            - Check the full changelog for detailed information about this release

            **Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}

  notify:
    name: Notify Success
    runs-on: ubuntu-latest
    needs: [publish]
    if: success()
    steps:
      - name: Notification
        run: |
          echo "🎉 Successfully published Typicord ${{ github.ref_name }} to npm!"
          echo "📦 Package: https://www.npmjs.com/package/typicord"
          echo "🔗 GitHub: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
